### ISSUE TITLE
Problem importing AWS OIDC Provider

### ISSUE THREAD

**Issue by orcutt989** [pulumi/pulumi-aws#1748]
```
pulumi import aws:iam/openIdConnectProvider:OpenIdConnectProvider stack-oidcProvider arn:aws:iam::<ACCOUNT_ID>:oidc-provider/oidc.eks.us-east-2.amazonaws.com/id/<OIDC_UID>
Previewing import (stack/name)

     Type                              Name                      Plan       Info
     pulumi:pulumi:Stack               company-stack             1 error
 =   └─ aws:iam:OpenIdConnectProvider  stack-oidcProvider  import     2 errors

Diagnostics:
  aws:iam:OpenIdConnectProvider (stack-oidcProvider):
    error: aws:iam/openIdConnectProvider:OpenIdConnectProvider resource 'stack-oidcProvider' has a problem: "url" has to use HTTPS scheme (i.e. begin with https://). Examine values at 'OpenIdConnectProvider.Url'.
    error: Preview failed: one or more inputs failed to validate

  pulumi:pulumi:Stack (stack-stack):
    error: preview failed
```

This command is constructed according to https://www.pulumi.com/registry/packages/aws/api-docs/iam/openidconnectprovider/#import

I can confirm that my url starts with HTTPS with an `aws eks describe-cluster --name cluster-name  --query "cluster.identity.oidc.issuer" --output text`

When I do a `aws iam get-open-id-connect-provider --open-id-connect-provider-arn arn:aws:iam::<ACCOUNT_ID>:oidc-provider/oidc.eks.us-east-2.amazonaws.com/id/<OIDC_UID>` the `URL` does not begin with HTTPS. 

Is it a bug or am I doing something wrong? Thanks!

**Pulumi Version: 3.20.0**

Package.json
```
{
    "name": "stack",
    "devDependencies": {
        "@types/node": "^16.9.6"
    },
    "dependencies": {
        "@pulumi/awsx": "^0.31.0",
        "@pulumi/eks": "^0.33.0",
        "@pulumi/pulumi": "^3.12.0",
        "dotenv": "^10.0.0",
        "yaml": "^1.10.2"
    }
}
```

**Comment by aureq** [comment]
To add more to this, it appears AWs doesn't specify the URL scheme as part of the `Url` property. A quick way to check this is to use the AWS cli to retrieve the OIDC.

`aws iam get-open-id-connect-provider --open-id-connect-provider-arn arn:aws:iam::<AWS_ACCOUNT_ID>:oidc-provider/oidc.eks.ap-southeast-2.amazonaws.com/id/<OIDC_UID>`

The the out is as follows:
```json
{
    "Url": "oidc.eks.ap-southeast-2.amazonaws.com/id/<OIDC_UID>",
    "ClientIDList": [
        "sts.amazonaws.com"
    ],
    "ThumbprintList": [
        "9e99a48a9960b14926bb7f3b02e22da2b0ab7280"
    ],
    "CreateDate": "2021-12-24T01:35:40.251000+00:00",
    "Tags": []
}
```

Looking into the code, The function responsible for validating the URL is located here: https://github.com/pulumi/terraform-provider-aws/blob/pulumi-master/aws/validators.go#L1388-L1402

```go
func validateOpenIdURL(v interface{}, k string) (ws []string, errors []error) {
	value := v.(string)
	u, err := url.Parse(value)
	if err != nil {
		errors = append(errors, fmt.Errorf("%q has to be a valid URL", k))
		return
	}
	if u.Scheme != "https" {
		errors = append(errors, fmt.Errorf("%q has to use HTTPS scheme (i.e. begin with https://)", k))
	}
	if len(u.Query()) > 0 {
		errors = append(errors, fmt.Errorf("%q cannot contain query parameters per the OIDC standard", k))
	}
	return
}
```

**Comment by mikhailshilkov** [comment]
Import functionality has been significantly refactored in #8922 to substantially reduce the number of failures during `pulumi import` and make the generated code more truthful and complete. We haven't tested this exact issue, but we believe it's addressed by the refactoring.

I'll go ahead and close the issue - feel free if you still get issues with it after upgrading to the Pulumi CLI version 3.26.1 or above.

Read more about the changes in [Easier IaC adoption with improved `pulumi import` experience](https://www.pulumi.com/blog/changes-to-import/).

**Comment by ryan-dyer-sp** [comment]
This still appears to be broken (or perhaps new issue with similar results).

```
pulumi import aws:iam/openIdConnectProvider:OpenIdConnectProvider GithubActionsOIDCProvider arn:aws:iam::<id>:oidc-provider/token.actions.githubusercontent.com
Previewing import (ops):
     Type                              Name                       Plan       Info
 +   pulumi:pulumi:Stack               github-actions-ops         create
 =   └─ aws:iam:OpenIdConnectProvider  GithubActionsOIDCProvider  import     2 warnings

Diagnostics:
  aws:iam:OpenIdConnectProvider (GithubActionsOIDCProvider):
    warning: One or more imported inputs failed to validate. This is almost certainly a bug in the `aws` provider. The import will still proceed, but you will need to edit the generated code after copying it into your program.
    warning: aws:iam/openIdConnectProvider:OpenIdConnectProvider resource 'GithubActionsOIDCProvider' has a problem: expected "url" to have a host, got token.actions.githubusercontent.com. Examine values at 'GithubActionsOIDCProvider.url'.

Resources:
    + 1 to create
    = 1 to import
    2 changes

Do you want to perform this import? yes
Importing (ops):
     Type                              Name                       Status               Info
 +   pulumi:pulumi:Stack               github-actions-ops         created
 =   └─ aws:iam:OpenIdConnectProvider  GithubActionsOIDCProvider  imported (0.82s)     2 warnings

Diagnostics:
  aws:iam:OpenIdConnectProvider (GithubActionsOIDCProvider):
    warning: One or more imported inputs failed to validate. This is almost certainly a bug in the `aws` provider. The import will still proceed, but you will need to edit the generated code after copying it into your program.
    warning: aws:iam/openIdConnectProvider:OpenIdConnectProvider resource 'GithubActionsOIDCProvider' has a problem: expected "url" to have a host, got token.actions.githubusercontent.com. Examine values at 'GithubActionsOIDCProvider.url'.

Resources:
    + 1 created
    = 1 imported
    2 changes

Duration: 5s

Please copy the following code into your Pulumi application. Not doing so
will cause Pulumi to report that an update will happen on the next update command.

Please note that the imported resources are marked as protected. To destroy them
you will need to remove the `protect` option and run `pulumi update` *before*
the destroy will take effect.

import pulumi
import pulumi_aws as aws

github_actions_oidc_provider = aws.iam.OpenIdConnectProvider("GithubActionsOIDCProvider",
    client_id_lists=["sts.amazonaws.com"],
    thumbprint_lists=["<thumbprint_id>"],
    url="token.actions.githubusercontent.com",
    opts = pulumi.ResourceOptions(protect=True))
```

Attempts to use this code and `pulumi up` result in errors as the url doesnt seem to match the expected values.  Trying to change the value to https://... results in it wanting to recreate the provider.  This is a valid OIDC provider which works as we expect it to and am simply looking to codify this provider.

Thanks

**Comment by Andrey36652** [comment]
@mikhailshilkov  I was in the process of migrating our infrastructure to Pulumi when I ran into ~the exact same~ kinda similar issue as described by @ryan-dyer-sp . Could you take a look?

**Upd:** I got same warning on import:
```
warning: One or more imported inputs failed to validate. This is almost certainly a bug in the `aws` provider. The import will still proceed, but you will need to edit the generated code after copying it into your program.
warning: aws:iam/openIdConnectProvider:OpenIdConnectProvider resource 'OIDCProvider' has a problem: expected "url" to have a host, got oidc.eks.eu-central-1.amazonaws.com/id/<redacted>. Examine values at 'OIDCProvider.url'.
```

But after I manually prepended `https://` to "url" arg (in python code) Pulumi (on `pulumi up`) sees no differences with existing (imported - the one without `https://`) state and does not try to recreate the provider. 
Sorry for ping.
