### ISSUE TITLE
Questions about Naming & Possible Resource Replacement Bug

### ISSUE THREAD

**Issue by armenr** [pulumi/pulumi-aws#642]
## Code Example:

const myDNSZone = new aws.route53.Zone('redactedDomain.me', {
  comment: 'My primary DNS Zone',
});

## What it builds:
```
{
  "comment": "My primary DNS Zone",
  "delegationSetId": "",
  "forceDestroy": false,
  "id": "REDACTED",
  "name": "redactedDomain.me-5fff4ae.",
  "nameServers": [
    "REDACTED.awsdns-24.org",
    "REDACTED.awsdns-41.co.uk",
    "REDACTED.awsdns-37.com",
    "REDACTED.awsdns-48.net"
  ],
  "tags": {},
  "vpcs": [],
  "zoneId": "REDACTED"
}

```

## My Question:
What's with the `-5fff4ae`?

Will this actually break DNS, or is it okay to have strings like this in the name, anyway? Couldn't find an answer so I figured I's ask.

**Comment by stack72** [comment]
Hi @armenr 	

So, by default, Pulumi actually randomizes the resource that you are trying to use. What you can do in this case, is to actually specify a real name as follows:

```
const myDNSZone = new aws.route53.Zone('my-primary-domain', {
  name: 'redactedDomain.me',
  comment: 'My primary DNS Zone',
});
```

That should give you the behaviour you are expecting - please try this and see how you do

Paul

**Comment by armenr** [comment]
Excellent!! Thank you Paul! This worked! :)

Not to sound like a dick, but the documentation/examples didn't make that easy to understand, although I should have absolutely tested more deeply and exampled the Opts/Args the Class takes.

Additionally, I'm struggling to understand how to create an MX record. Generally, MX records.

```
const myDNSZone = new aws.route53.Zone('myDomain.me', {
  comment: 'redactedDomain primary DNS Zone',
});

export const dnsZoneName = myDNSZone.name;

const MX = new aws.route53.Record('', {
  records: ['1 ASPMX.L.GOOGLE.COM'],
  ttl: 300,
  type: 'MX',
  zoneId: myDNSZone.zoneId,
});
```

## Output:

```
 Error: Missing resource name argument (for URN creation)
```

I'm guessing that first string param we're passing as the argument is the URN "name" and not the "name" of the record, actually in AWS.

In this case, how does one assign, let's say, 1 or many MX records with the numerical preference value for prioritization?

Thanks again for all the help!! :)

**Comment by armenr** [comment]
Your last post also helped me demystify the SAME 'random-string' assignment problem I was having with my Application LoadBalancer. THANK YOU!

Again, not to sound like a dick, but if the documentation/examples made the user aware/cautious of this random-string-assignment tendency, that would be really really helpful. :)

**Comment by armenr** [comment]
Additionally, we may have to change the scope of this Issue, as this I've now run into a different bug. I am not sure, but would this specific issue I'm about to share be solved with a "CreateBeforeDestroy" parameter?

```Do you want to perform this update? yes
Updating (dev):

     Type                                                      Name                                  Status                   Info
     pulumi:pulumi:Stack                                       myInfra-tessitura-dev                    **failed**               1 error
 +   ├─ awsx:x:ec2:SecurityGroup                               dev-loadbalancer                      created
 +   │  └─ aws:ec2:SecurityGroup                               dev-loadbalancer                      created
 +   └─ awsx:x:elasticloadbalancingv2:ApplicationLoadBalancer  dev-loadbalancer                      created
        ├─ awsx:x:elasticloadbalancingv2:ApplicationListener   dev-ssl-listener
        │  ├─ awsx:x:ec2:IngressSecurityGroupRule              dev-ssl-listener-external-0-ingress
 +-     │  │  └─ aws:ec2:SecurityGroupRule                     dev-ssl-listener-external-0-ingress   replaced                 [diff: ~securityGroupId]
        │  ├─ awsx:x:ec2:EgressSecurityGroupRule               dev-ssl-listener-external-0-egress
 +-     │  │  └─ aws:ec2:SecurityGroupRule                     dev-ssl-listener-external-0-egress    replaced                 [diff: ~securityGroupId]
 +-     │  └─ aws:elasticloadbalancingv2:Listener              dev-ssl-listener                      **replacing failed**     [diff: ~loadBalancerArn]; 1 error
        ├─ awsx:x:elasticloadbalancingv2:ApplicationListener   dev-http-listener
        │  ├─ awsx:x:ec2:EgressSecurityGroupRule               dev-http-listener-external-0-egress
 +-     │  │  └─ aws:ec2:SecurityGroupRule                     dev-http-listener-external-0-egress   replaced                 [diff: ~securityGroupId]
        │  ├─ awsx:x:ec2:IngressSecurityGroupRule              dev-http-listener-external-0-ingress
 +-     │  │  └─ aws:ec2:SecurityGroupRule                     dev-http-listener-external-0-ingress  replaced                 [diff: ~securityGroupId]
 +-     │  └─ aws:elasticloadbalancingv2:Listener              dev-http-listener                     replaced                 [diff: ~loadBalancerArn]
 +      └─ aws:elasticloadbalancingv2:LoadBalancer             dev-loadbalancer                      created

Diagnostics:
  pulumi:pulumi:Stack (myInfra-tessitura-dev):
    error: update failed

  aws:elasticloadbalancingv2:Listener (dev-ssl-listener):
    error: Plan apply failed: Error creating LB Listener: TargetGroupAssociationLimit: Target group 'arn:aws:elasticloadbalancing:us-west-2:491419166139:targetgroup/ece2b6a8-c953153/9f1879893ee9c1b5' cannot be associated with more than one load balancer
    	status code: 400, request id: b91788e5-9e45-11e9-b03f-7778c7ba4e5d```

When adding the "name" property to my existing ALB, the "update" operation on existing resources breaks, and sits in a broken state.

I had to completely destroy the existing ALB module and listeners, then recreate them. Would the "CreateBeforeDestroy" hook be the way to handle this here? Or is this an actual bug? :)

**Comment by stack72** [comment]
Hi @armenr 	

Glad this is working better for you. I understand the frustration here - I will raise it internally and see what we need to do to be better here. 

So for the MX records, you still need to provide a name to the struct otherwise pulumi won't be able to store the resource. So you app could look as follows:

```
const myDNSZone = new aws.route53.Zone('myDomain.me', {
  comment: 'redactedDomain primary DNS Zone',
});

export const dnsZoneName = myDNSZone.name;

const MX = new aws.route53.Record('google-mx', {
  records: ['1 ASPMX.L.GOOGLE.COM'],
  ttl: 300,
  type: 'MX',
  zoneId: myDNSZone.zoneId,
});
```

That will create the correct r53 request to AWS for you

**Comment by armenr** [comment]
^^ thank you! 

I did go back and find this: https://www.pulumi.com/docs/reference/programming-model/#autonaming

But it's a bit...hidden. I guess I am a dick :)

**Comment by stack72** [comment]
haha you are not! We should make it much more clear!

All sorted? OR you still having an issue?

P.

**Comment by armenr** [comment]
@stack72 - My LAST question is this:

I've got my ALB resource looking like this:
```
const myALB = new awsx.elasticloadbalancingv2.ApplicationLoadBalancer(nameFactory('loadbalancer'), {
  // https://pulumi.io/reference/pkg/nodejs/pulumi/awsx/elasticloadbalancingv2/#ApplicationLoadBalancer
  name: nameFactory('loadbalancer'),
  vpc: myVPC,
  enableHttp2: true,
  external: true,
});
```
For the record, the `nameFactory` function is a simple and naive function that accepts a resourceName string, and prepends my deploy stage string to my named resources - e.g. `dev-loadbalancer` or `prod-loadbalancer`

When I attempt to pass in a third options object with `{ deleteBeforeReplace: true }` I get the following error:
```
    src/index.ts(49,5): error TS2345: Argument of type '{ deleteBeforeReplace: boolean; }' is not assignable to parameter of type 'ComponentResourceOptions'.
      Object literal may only specify known properties, and 'deleteBeforeReplace' does not exist in type 'ComponentResourceOptions'.
```

**Comment by stack72** [comment]
@armenr there is actually no way to pass `deleteBeforeReplace` to those providers. the opts arg is `ComponentResourceOptions` which extends `ResourceOptions`

ResourceOptions has the following:

```
export interface ResourceOptions {
    /**
     * An optional existing ID to load, rather than create.
     */
    id?: Input<ID>;
    /**
     * An optional parent resource to which this resource belongs.
     */
    parent?: Resource;
    /**
     * An optional additional explicit dependencies on other resources.
     */
    dependsOn?: Input<Input<Resource>[]> | Input<Resource>;
    /**
     * When set to true, protect ensures this resource cannot be deleted.
     */
    protect?: boolean;
    /**
     * Ignore changes to any of the specified properties.
     */
    ignoreChanges?: string[];
    /**
     * An optional version, corresponding to the version of the provider plugin that should be used when operating on
     * this resource. This version overrides the version information inferred from the current package and should
     * rarely be used.
     */
    version?: string;
    /**
     * An optional list of aliases to treat this resource as matching.
     */
    aliases?: Input<URN | Alias>[];
    /**
     * An optional provider to use for this resource's CRUD operations. If no provider is supplied,
     * the default provider for the resource's package will be used. The default provider is pulled
     * from the parent's provider bag (see also ComponentResourceOptions.providers).
     *
     * If this is a [ComponentResourceOptions] do not provide both [provider] and [providers]
     */
    provider?: ProviderResource;
}
```

**Comment by armenr** [comment]
Ah, I see.

In that case, would the behavior or "renaming" the the existing ALB resource and having it crash out on us be considered a bug? 

Else, how would I go about enforcing that kind of constraint on the resource to prevent updates from breaking halfway.

**Comment by stack72** [comment]
Can you give me a little code I can try to recreate this? I can have a look at this and see if it's a breakage

**Comment by armenr** [comment]
Here's the code! REALLY appreciate your assistance on this! Thank you!

## vpc.ts
```
import * as pulumi from '@pulumi/pulumi';
import * as aws from '@pulumi/aws';
import * as awsx from '@pulumi/awsx';
import * as config from '../utils/config';

export default function() {
  return new awsx.ec2.Vpc(`${config.ENV_STAGE}`, {
    subnets: [
      { type: 'public', assignIpv6AddressOnCreation: false },
      { type: 'private', assignIpv6AddressOnCreation: false },
      { type: 'isolated', name: 'redis', assignIpv6AddressOnCreation: false },
    ],
    numberOfNatGateways: 1,
    cidrBlock: '10.0.0.0/16',
    enableDnsSupport: true,
    enableDnsHostnames: true,
    tags: {
      Environment: `${config.ENV_STAGE}`,
      InfraVersion: `${config.INFRA_VERSION}`,
      // ProvisionedAt: ts.toUTCString(), //TODO: FIGURE OUT A WAY TO DO THIS ONLY ONCE!
    },
  });
}
```

## index.ts (I know, it's not modularized or EVEN sophisticated yet)
```
// this goes here for later: https://blog.pulumi.com/testing-your-infrastructure-as-code-with-pulumi

import * as shell from 'shelljs';
import * as pulumi from '@pulumi/pulumi';
import * as aws from '@pulumi/aws';
import * as awsx from '@pulumi/awsx';
import * as config from './utils/config';
import createVPC from './modules/vpc';

// Yay pointless timeStamping utility
const ts = new Date();

const nameFactory = (resourceParam: string) => {
  return `${config.ENV_STAGE}` + '-' + resourceParam;
};

// // Create Bucket
const Bucket = new aws.s3.Bucket(`${config.ENV_BUCKET}`);

// Create VPC
const myVPC = createVPC();

// Create ApplicationLoadBalancer & Attach Listeners
const myALB = new awsx.elasticloadbalancingv2.ApplicationLoadBalancer(nameFactory('loadbalancer'), {
  // https://pulumi.io/reference/pkg/nodejs/pulumi/awsx/elasticloadbalancingv2/#ApplicationLoadBalancer
  vpc: myVPC,
  enableHttp2: true,
  external: true,
});

const SSLListener = myALB.createListener(nameFactory('ssl-listener'), {
  port: 443,
  protocol: 'HTTPS',
  certificateArn: `${config.MY_SSL_ARN}`,
  sslPolicy: 'ELBSecurityPolicy-FS-2018-06',
});

const httpListener = myALB.createListener(nameFactory('http-listener'), {
  port: 80,
  protocol: 'HTTP',
  defaultAction: {
    type: 'redirect',
    redirect: {
      protocol: 'HTTPS',
      port: '443',
      statusCode: 'HTTP_301',
    },
  },
});
```

So, the way I hit the bug was the following:

The ALB had been created, but without the "name:" property inside the config object.
When I added the "name" property to the config object, it said..."I gotta replace this dude."
I was like "sure. do that"

So, the above ALB code changed to:
```
const myALB = new awsx.elasticloadbalancingv2.ApplicationLoadBalancer(nameFactory('loadbalancer'), {
  // https://pulumi.io/reference/pkg/nodejs/pulumi/awsx/elasticloadbalancingv2/#ApplicationLoadBalancer
  name: nameFactory('loadbalancer'),
  vpc: myVPC,
  enableHttp2: true,
  external: true,
});
```

When it kicked off the update, it came back and threw:
```
  aws:elasticloadbalancingv2:Listener (dev-ssl-listener):
    error: Plan apply failed: Error creating LB Listener: TargetGroupAssociationLimit: Target group 'arn:aws:elasticloadbalancing:us-west-2:491419166139:targetgroup/ece2b6a8-c953153/9f1879893ee9c1b5' cannot be associated with more than one load balancer
    	status code: 400, request id: b91788e5-9e45-11e9-b03f-7778c7ba4e5d
```

So then, I said, let me modify my ALB code to add "deleteBeforeReplace," assuming that this would help mitigate this kind of problem:

```
const myALB = new awsx.elasticloadbalancingv2.ApplicationLoadBalancer(
  nameFactory('loadbalancer'),
  {
    // https://pulumi.io/reference/pkg/nodejs/pulumi/awsx/elasticloadbalancingv2/#ApplicationLoadBalancer
    name: nameFactory('loadbalancer'),
    vpc: myVPC,
    enableHttp2: true,
    external: true,
  },
  { deleteBeforeReplace: true },
);
```
At that point, pulumi logs:
```
    src/index.ts(49,5): error TS2345: Argument of type '{ deleteBeforeReplace: boolean; }' is not assignable to parameter of type 'ComponentResourceOptions'.
```

Please let me know in case you need anything else. :)

**Comment by armenr** [comment]
Not to spam you, but I think this might actually help.

Just as a ham-fisted experiment, I attempted to rename my VPC. It threw again - same error - specifically on the TargetGroup resource, again. This looks endemic to TargetGroup resources.

## Plan:
```
Previewing update (dev):

     Type                                                        Name                                  Plan        Info
     pulumi:pulumi:Stack                                         myInfra-tessitura-dev                  running
 +   ├─ awsx:x:ec2:Vpc                                           dev-vpc                               create
 +   │  ├─ awsx:x:ec2:Subnet                                     dev-vpc-public-0                      create
 +   │  │  ├─ aws:ec2:RouteTable                                 dev-vpc-public-0                      create
 +   │  │  ├─ aws:ec2:Route                                      dev-vpc-public-0-ig                   create
 +   │  │  ├─ aws:ec2:Subnet                                     dev-vpc-public-0                      create
 +   │  │  └─ aws:ec2:RouteTableAssociation                      dev-vpc-public-0                      create
 +   │  ├─ awsx:x:ec2:Subnet                                     dev-vpc-redis-isolated-0              create
 +   │  │  ├─ aws:ec2:RouteTable                                 dev-vpc-redis-isolated-0              create
 +   │  │  ├─ aws:ec2:Subnet                                     dev-vpc-redis-isolated-0              create
 +   │  │  └─ aws:ec2:RouteTableAssociation                      dev-vpc-redis-isolated-0              create
 +   │  ├─ awsx:x:ec2:Subnet                                     dev-vpc-private-1                     create
 +   │  │  ├─ aws:ec2:RouteTable                                 dev-vpc-private-1                     create
 +   │  │  ├─ aws:ec2:Subnet                                     dev-vpc-private-1                     create
 +   │  │  ├─ aws:ec2:RouteTableAssociation                      dev-vpc-private-1                     create
 +   │  │  └─ aws:ec2:Route                                      dev-vpc-private-1-nat-1               create
 +   │  ├─ awsx:x:ec2:Subnet                                     dev-vpc-private-0                     create
 +   │  │  ├─ aws:ec2:RouteTable                                 dev-vpc-private-0                     create
 +   │  │  ├─ aws:ec2:Subnet                                     dev-vpc-private-0                     create
 +   │  │  ├─ aws:ec2:RouteTableAssociation                      dev-vpc-private-0                     create
 +   │  │  └─ aws:ec2:Route                                      dev-vpc-private-0-nat-0               create
 +   │  ├─ awsx:x:ec2:NatGateway                                 dev-vpc-0                             create
 +   │  │  ├─ aws:ec2:Eip                                        dev-vpc-0                             create
     pulumi:pulumi:Stack                                         myInfra-tessitura-dev
 +   │  ├─ awsx:x:ec2:InternetGateway                            dev-vpc                               create
 +   │  │  └─ aws:ec2:InternetGateway                            dev-vpc                               create
 +   │  ├─ awsx:x:ec2:Subnet                                     dev-vpc-public-1                      create
 +   │  │  ├─ aws:ec2:RouteTable                                 dev-vpc-public-1                      create
 +   │  │  ├─ aws:ec2:Route                                      dev-vpc-public-1-ig                   create
 +   │  │  ├─ aws:ec2:Subnet                                     dev-vpc-public-1                      create
 +   │  │  └─ aws:ec2:RouteTableAssociation                      dev-vpc-public-1                      create
 +   │  └─ awsx:x:ec2:Subnet                                     dev-vpc-redis-isolated-1              create
 +   │     ├─ aws:ec2:RouteTable                                 dev-vpc-redis-isolated-1              create
 +   │     ├─ aws:ec2:Subnet                                     dev-vpc-redis-isolated-1              create
 +   │     └─ aws:ec2:RouteTableAssociation                      dev-vpc-redis-isolated-1              create
 +   ├─ aws:ec2:Vpc                                              dev-vpc                               create
     ├─ awsx:x:ec2:SecurityGroup                                 dev-loadbalancer
 +-  │  └─ aws:ec2:SecurityGroup                                 dev-loadbalancer                      replace     [diff: ~name,vpcId]
     ├─ awsx:x:elasticloadbalancingv2:ApplicationLoadBalancer    dev-loadbalancer
     │  ├─ awsx:x:elasticloadbalancingv2:ApplicationTargetGroup  dev-ssl-listener
 +-  │  │  └─ aws:elasticloadbalancingv2:TargetGroup             dev-ssl-listener                      replace     [diff: ~vpcId]
     │  ├─ awsx:x:elasticloadbalancingv2:ApplicationListener     dev-ssl-listener
     │  │  ├─ awsx:x:ec2:EgressSecurityGroupRule                 dev-ssl-listener-external-0-egress
 +-  │  │  │  └─ aws:ec2:SecurityGroupRule                       dev-ssl-listener-external-0-egress    replace     [diff: ~securityGroupId]
     │  │  ├─ awsx:x:ec2:IngressSecurityGroupRule                dev-ssl-listener-external-0-ingress
 +-  │  │  │  └─ aws:ec2:SecurityGroupRule                       dev-ssl-listener-external-0-ingress   replace     [diff: ~securityGroupId]
 +-  │  │  └─ aws:elasticloadbalancingv2:Listener                dev-ssl-listener                      replace     [diff: ~defaultActions,loadBalancerArn]
     │  ├─ awsx:x:elasticloadbalancingv2:ApplicationListener     dev-http-listener
     │  │  ├─ awsx:x:ec2:IngressSecurityGroupRule                dev-http-listener-external-0-ingress
 +-  │  │  │  └─ aws:ec2:SecurityGroupRule                       dev-http-listener-external-0-ingress  replace     [diff: ~securityGroupId]
     │  │  ├─ awsx:x:ec2:EgressSecurityGroupRule                 dev-http-listener-external-0-egress
 +-  │  │  │  └─ aws:ec2:SecurityGroupRule                       dev-http-listener-external-0-egress   replace     [diff: ~securityGroupId]
 +-  │  │  └─ aws:elasticloadbalancingv2:Listener                dev-http-listener                     replace     [diff: ~loadBalancerArn]
 ~   │  └─ aws:elasticloadbalancingv2:LoadBalancer               dev-loadbalancer                      update      [diff: ~securityGroups,subnets]
 ~   ├─ aws:elasticache:SubnetGroup                              dev-sessionSubnets                    update      [diff: ~subnetIds]
 +-  ├─ aws:elasticache:ReplicationGroup                         dev-sessions                          replace     [diff: ~replicationGroupId,subnetGroupName]
 -   ├─ awsx:x:ec2:Vpc                                           dev                                   delete
 -   │  ├─ awsx:x:ec2:InternetGateway                            dev                                   delete
 -   │  │  └─ aws:ec2:InternetGateway                            dev                                   delete
 -   │  ├─ awsx:x:ec2:NatGateway                                 dev-0                                 delete
 -   │  │  ├─ aws:ec2:NatGateway                                 dev-0                                 delete
 -   │  │  └─ aws:ec2:Eip                                        dev-0                                 delete
 -   │  ├─ awsx:x:ec2:Subnet                                     dev-public-0                          delete
 -   │  │  ├─ aws:ec2:RouteTableAssociation                      dev-public-0                          delete
 -   │  │  ├─ aws:ec2:Route                                      dev-public-0-ig                       delete
 -   │  │  ├─ aws:ec2:Subnet                                     dev-public-0                          delete
 -   │  │  └─ aws:ec2:RouteTable                                 dev-public-0                          delete
 -   │  ├─ awsx:x:ec2:Subnet                                     dev-redis-isolated-1                  delete
 -   │  │  ├─ aws:ec2:RouteTableAssociation                      dev-redis-isolated-1                  delete
 -   │  │  ├─ aws:ec2:RouteTable                                 dev-redis-isolated-1                  delete
 -   │  │  └─ aws:ec2:Subnet                                     dev-redis-isolated-1                  delete
 -   │  ├─ awsx:x:ec2:Subnet                                     dev-public-1                          delete
 -   │  │  ├─ aws:ec2:RouteTableAssociation                      dev-public-1                          delete
 -   │  │  ├─ aws:ec2:Route                                      dev-public-1-ig                       delete
 -   │  │  ├─ aws:ec2:Subnet                                     dev-public-1                          delete
 -   │  │  └─ aws:ec2:RouteTable                                 dev-public-1                          delete
 -   │  ├─ awsx:x:ec2:Subnet                                     dev-redis-isolated-0                  delete
 -   │  │  ├─ aws:ec2:RouteTableAssociation                      dev-redis-isolated-0                  delete
 -   │  │  ├─ aws:ec2:RouteTable                                 dev-redis-isolated-0                  delete
 -   │  │  └─ aws:ec2:Subnet                                     dev-redis-isolated-0                  delete
 -   │  ├─ awsx:x:ec2:Subnet                                     dev-private-0                         delete
 -   │  │  ├─ aws:ec2:Route                                      dev-private-0-nat-0                   delete
 -   │  │  ├─ aws:ec2:RouteTableAssociation                      dev-private-0                         delete
 -   │  │  ├─ aws:ec2:Subnet                                     dev-private-0                         delete
 -   │  │  └─ aws:ec2:RouteTable                                 dev-private-0                         delete
 -   │  └─ awsx:x:ec2:Subnet                                     dev-private-1                         delete
 -   │     ├─ aws:ec2:Route                                      dev-private-1-nat-1                   delete
 -   │     ├─ aws:ec2:RouteTableAssociation                      dev-private-1                         delete
 -   │     ├─ aws:ec2:RouteTable                                 dev-private-1                         delete
 -   │     └─ aws:ec2:Subnet                                     dev-private-1                         delete
 -   └─ aws:ec2:Vpc                                              dev                                   delete
```

## Output and Error:
```
Updating (dev):

     Type                                                        Name                      Status                   Info
     pulumi:pulumi:Stack                                         gruv-tessitura-dev        **failed**               1 error
 +   ├─ awsx:x:ec2:Vpc                                           dev-vpc                   created
 +   │  ├─ awsx:x:ec2:Subnet                                     dev-vpc-public-0          created
 +   │  │  ├─ aws:ec2:RouteTable                                 dev-vpc-public-0          created
 +   │  │  └─ aws:ec2:Subnet                                     dev-vpc-public-0          created
 +   │  ├─ awsx:x:ec2:Subnet                                     dev-vpc-private-0         created
 +   │  │  ├─ aws:ec2:RouteTable                                 dev-vpc-private-0         created
 +   │  │  └─ aws:ec2:Subnet                                     dev-vpc-private-0         created
 +   │  ├─ awsx:x:ec2:Subnet                                     dev-vpc-redis-isolated-0  created
 +   │  │  ├─ aws:ec2:RouteTable                                 dev-vpc-redis-isolated-0  created
 +   │  │  └─ aws:ec2:Subnet                                     dev-vpc-redis-isolated-0  created
 +   │  ├─ awsx:x:ec2:Subnet                                     dev-vpc-public-1          created
 +   │  │  ├─ aws:ec2:RouteTable                                 dev-vpc-public-1          created
 +   │  │  └─ aws:ec2:Subnet                                     dev-vpc-public-1          created
 +   │  ├─ awsx:x:ec2:Subnet                                     dev-vpc-private-1         created
 +   │  │  ├─ aws:ec2:RouteTable                                 dev-vpc-private-1         created
 +   │  │  └─ aws:ec2:Subnet                                     dev-vpc-private-1         created
 +   │  ├─ awsx:x:ec2:Subnet                                     dev-vpc-redis-isolated-1  created
 +   │  │  ├─ aws:ec2:RouteTable                                 dev-vpc-redis-isolated-1  created
 +   │  │  └─ aws:ec2:Subnet                                     dev-vpc-redis-isolated-1  created
 +   │  ├─ awsx:x:ec2:InternetGateway                            dev-vpc                   created
 +   │  │  └─ aws:ec2:InternetGateway                            dev-vpc                   created
 +   │  └─ awsx:x:ec2:NatGateway                                 dev-vpc-0                 created
 +   │     └─ aws:ec2:Eip                                        dev-vpc-0                 created
 +   ├─ aws:ec2:Vpc                                              dev-vpc                   created
     ├─ awsx:x:ec2:SecurityGroup                                 dev-loadbalancer
 +-  │  └─ aws:ec2:SecurityGroup                                 dev-loadbalancer          replaced                 [diff: ~name,vpcId]
     └─ awsx:x:elasticloadbalancingv2:ApplicationLoadBalancer    dev-loadbalancer
        └─ awsx:x:elasticloadbalancingv2:ApplicationTargetGroup  dev-ssl-listener
 +-        └─ aws:elasticloadbalancingv2:TargetGroup             dev-ssl-listener          **replacing failed**     [diff: ~vpcId]; 1 error

Diagnostics:
  pulumi:pulumi:Stack (myInfra-tessitura-dev):
    error: update failed

  aws:elasticloadbalancingv2:TargetGroup (dev-ssl-listener):
    error: Plan apply failed: Error creating LB Target Group: DuplicateTargetGroupName: A target group with the same name 'dev-ssl-listener' exists, but with different settings
    	status code: 400, request id: b6e3c602-9e55-11e9-985e-49c8fde33394

Resources:
    + 24 created
    12 unchanged
```

**Comment by armenr** [comment]
^^ This was probably a bad experiment. The entire infra state is now broken. A pulumi destroy on the entirety of the infrastructure is now hung on:

```
Resources:
    - 83 to delete

Do you want to perform this destroy? yes
Destroying (dev):

     Type                      Name                Status       Info
     pulumi:pulumi:Stack       myInfra-tessitura-dev
 -   └─ aws:ec2:SecurityGroup  dev-loadbalancer    deleting..   completing deletion from previous update
```

**Comment by stack72** [comment]
Hi @armenr 

Is this something you still need help in working out or can I close this out?

Paul

**Comment by armenr** [comment]
All good! Everything works as expected since the latest few updates :)

**Comment by donald-richardson-dxd** [comment]
Sorry to reopen this but I'm experiencing the same TargetGroup issues. @armenr Did you ever resolve this? You say that "everything works as expected since the last few updates" but I'm using v3.46.1 and am experiencing the issue.
